import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000"  # Backend endpoint

st.set_page_config(
    page_title="Travel Planner Agentic Application",
    page_icon="",
    layout="centered",
    initial_sidebar_state="expanded"

)

st.title("Travel Planner Agentic Application")

# Intialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []

# Desplay Header
st.header("How can I help you in planning a trip? Let me know where do you want to visit.")

with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("user Input", placeholder="e.g. Plan a trip to Goa for 5 days.")
    submit_button = st.form_submit_button("Send")

if submit_button and user_input.strip():
    try:
        # show user message
        # show thinking spinner while backend processes
        with st.spinner("Thinking"):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/querry", json=payload)

        if response.status_code == 200:
            answer = response.json().get("answer","No answer returned.")
            markdown_content = f"""# AI Travel Plane 
            
            # ** Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}
            # **Created by:** Agentic AI Travel Agent

            ----

            {answer}

            ----

             *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*

            
            """

            st.markdown(markdown_content)
            
        else :
            st.error("Failed to respond:" + response.text)    
    except Exception as e:
        raise f"The response failed due to {e}"